### ISSUE TITLE
Bug: update file with existing filename will overwrite old file on storage.

### ISSUE THREAD

**Issue by favoyang** [aliyun/django-oss-storage#17]
Django's `storage.save` method invoked `get_available_name` method to avoid overwriting old file with same filename.

```
    def save(self, name, content, max_length=None):
        ...
        name = self.get_available_name(name, max_length=max_length)
        return self._save(name, content)
```

`OSSStaticStorage` and `OSSMediaStorage` backends both override the `save` method, and skip the logic by invoking `_save` method directly. Not sure it's a mistake or intended. This behavior caused bug when updating existing filename using `FileField`. The old file will be overwrote, the new one then be deleted (because Django thought it was deleting the old file).

Simply remove the overridden `save` method of `OSSStaticStorage` and `OSSMediaStorage` backends shall solve the issue.

This shall not affect collectstatic process which relying on `storage._save` method to overwrite existing file directly.

**Comment by huiguangjun** [comment]
fixed in version 1.1.1
