### ISSUE TITLE
Django 内部的 Storage.save 方法被覆盖，但丢掉了文件名防冲突的行为

### ISSUE THREAD

**Issue by wonderbeyond** [aliyun/django-oss-storage#21]
在 `OssMediaStorage` 和 `OssStaticStorage` 两个 Storage 子类中，save 方法被覆盖了，只是简单地调用了 `OssStorage` 的 `_save` 方式，而无视了 `django.core.files.storage.Storage.save` 提供的文件名放冲突行为。

---

建议 `OssMediaStorage` 和 `OssStaticStorage` 就不要定义 `save` 方法了，直接从 `django.core.files.storage.Storage` 继承就好，它会自动找一个不冲突的名字，然后调用子类的 `_save` 方法。

**Comment by wonderbeyond** [comment]
我直接在项目自己应用工程里面定义了一个子类找回了 Django 的默认行为：

myproject/storages.py:
```python
from django_oss_storage.backends import OssStorage

class OssMediaStorage(OssStorage):
    def __init__(self, location='media', **kwargs):
        self.location = location
        super(OssMediaStorage, self).__init__(**kwargs)
```

settings.py:
```python
DEFAULT_FILE_STORAGE = 'mysite.storages.OssMediaStorage'
```

**Comment by favoyang** [comment]
Duplicated with https://github.com/aliyun/django-oss-storage/issues/17.

**Comment by huiguangjun** [comment]
fixed in version 1.1.1
